# Generated by Django 6.0.6 on 2026-06-17 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('total_images', models.IntegerField(default=0)),
                ('passed_images', models.IntegerField(default=0)),
                ('failed_images', models.IntegerField(default=0)),
                ('avg_severity', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=100.0)),
                ('defect_rate', models.FloatField(default=0.0)),
                ('defect_distribution_json', models.TextField(default='{}')),
                ('report_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Batch Report',
                'verbose_name_plural': 'Batch Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAISSIndexMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_path', models.CharField(max_length=500)),
                ('num_vectors', models.IntegerField(default=0)),
                ('embedding_dim', models.IntegerField(default=2048)),
                ('built_at', models.DateTimeField(auto_now_add=True)),
                ('image_ids_json', models.TextField(default='[]')),
            ],
            options={
                'verbose_name': 'FAISS Index Metadata',
                'verbose_name_plural': 'FAISS Index Metadata',
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=500)),
                ('predicted_class', models.IntegerField(default=0)),
                ('defect_label', models.CharField(default='No Defect', max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('severity_score', models.FloatField(default=0.0)),
                ('severity_category', models.CharField(default='No Defect', max_length=50)),
                ('defect_area_pct', models.FloatField(default=0.0)),
                ('gradcam_path', models.CharField(blank=True, default='', max_length=500)),
                ('is_defective', models.BooleanField(default=False)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('batch_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='dashboard.batchreport')),
            ],
            options={
                'verbose_name': 'Inspection Result',
                'verbose_name_plural': 'Inspection Results',
                'ordering': ['-inspected_at'],
            },
        ),
    ]
